CREATE TABLE mega_descargas
(
    ID INTEGER PRIMARY KEY,
    URI_PUBLICO TEXT NOT NULL,
    FECHA DATETIME NOT NULL
);

CREATE TABLE mega_parametros
(
    Id INTEGER PRIMARY KEY NOT NULL,
    Clave TEXT NOT NULL,
    Valor TEXT NOT NULL
);
